### ISSUE TITLE
Off-Hand Syringe Bug

### ISSUE THREAD

**Issue by SilverShadow525** [TheUnderTaker11/GeneticsReborn#50] opened 2017-12-03 05:27 UTC
I had gotten a syringe ready with the "Shoot Fireballs" gene in the syringe, but when I tried to use it, I had food in my off-hand (so it chose the food over the syringe), so I switched the syringe to my off-hand slot and put my Diamond Pick in my main hand. I right-clicked to use the syringe again, but the syringe disappeared and a copy of the pickaxe appeared in my off-hand. I tried to grab the copy and put it into my inventory, but that disappeared too (not surprised really now that I think about it)!  At least for me it was only the shoot fireballs gene (I have the metamorph mod, and I have a blaze morph, so blazes aren't a problem for me, but I digress), but imagine the frustration that might come from losing one of the endermite genes or an ender dragon gene from that scenario! Can you see what you can do about it?

**Comment by alothmanmoe** [comment] 2017-12-13 03:35
Yeah ill take a look at it, probably will be fixed next update

**Comment by clubpetey** [comment] 2019-09-24 16:13
Cannot reproduce in current version either, this may have been a side-effect of the dupe-bug.

**Closed as completed by clubpetey** 2019-09-24 16:13 UTC
Labels: Can't Reproduce
