### ISSUE TITLE
Just to keep an eye out for this...

### ISSUE THREAD

**Issue by Drase333** [TheUnderTaker11/GeneticsReborn#16] opened 2017-01-17 02:40 UTC
Had a bug happen before i realized v .16 had came out, just wanted to mention it since I ran into it... Had a problem with the effects disappearing on me. The potion effect abilities (Resistance 2, jump boost, speed 2 and night vision) all disappeared for a little while. I only noticed when I couldn't high-step with the jump boost effect, so I'm not sure what caused it. Fire immunity and flight still worked fine though. Going through the portal to the nether didn't fix it, but it seemed like coming back to the overworld from the nether did. I can't seem to reproduce it though, I just wanted to bring it up to keep an eye out for.

**Comment by TheUnderTaker11** [comment] 2017-01-17 03:08
So they just went away all-together and didn't come back? Strange. v0.16 didn't change anything to do with those so if the problem happens again tell me, and state if you are on a server or not. I'll look at it a bit for now.

**Comment by TheUnderTaker11** [comment] 2017-01-17 03:12
Quick note, if it happens again, also test if the water breather gene is working (assuming you have it). Those are handled in almost the same way, so if you are able to drown that will get me a lot closer to the actual problem.
After you see this close the ticket and make a new one if you have the problem again. I'm not closing it myself since I want to make sure you read this.

**Comment by Drase333** [comment] 2017-01-17 17:57
It has happened again, even in v0.16. I think water breathing did still work for me the first time, and it seemed like coming to the overworld from the nether fixed it the second time as well. It seems to only be an issue with the abilities that are constantly refreshing potion effects, as far as I can tell. I'll keep you updated on when it happens and what i can figure out about it when it does. 

Oh, and I'm on single player, added the mod onto All the mods lite modpack. Loved the original this is based off of, was really happy to see a 1.10 remake.

Edit: it seems I have lost them again when going to the end, but I didn't really check until after the dragon was beaten. Will edit this post with more until you reply to it, to prevent a ton of posts
Edit2: Going back and forth between the overworld, nether, and end to see if it would fix the disappearing effects, I seem to have lost water breathing, flight, and fire immunity (when visiting the end again). Extra hearts seems to vanish at first, but once taken damage it registers properly again. Death also does not fix the issue, drowned my character to see if it would register any changes in effects.
Restarting the game also does not fix the issue.
Edit3: I was able to finally get back my genes from a syringe I had saved just in case I lost my genetics before. Previously when I had tried to get everything back using this method, It hadn't worked to get back resistance, night vision, speed, and boost, but with whatever bug caused me to also lose waterbreathing, flight, and fire resistance was fixed by re applying the effects through a syringe. I used to use the same method of saving an extra filled syringe with the original advanced genetics for 'just in case'
edit4: just noticed the extra hearts I received from the health boost gene seem to have doubled. Not gonna complain about it, but still a bug after my old genes were reapplied again.

**Comment by TheUnderTaker11** [comment] 2017-01-17 22:33
So you can't find an event that seems to trigger these things happening? This is really strange... it seems you are somehow losing the stored data on your player. Again if you are able to find a trigger that would be a world of help. I'll download that pack and try it out for awhile to see if I can re-produce the problem.
Normally I would say try the bug on a world with no other mods, but until you find a trigger idk.

**Comment by Drase333** [comment] 2017-01-17 22:50
I can't seem to pin down what's causing it, and it may just be compatibility issues somewhere along the line. It does take some time between occurrences though. It may be difficult to pin down, as I've added mods and changed some configs around in the original pack, but that would be the place to start. I haven't had the issue with other mods or normal potion effects, and as it only affects genetics reborn it seems to be either a bug or compatibility issue. I know that's not very helpful, but I want to give all the info I can to try and help with the mod.

**Comment by TheUnderTaker11** [comment] 2017-01-17 22:52
Downloaded the pack, reproduced it by going to the nether right after giving myself all genes. I'll keep testing.
EDIT: Genes like eat grass are kept for sure, so this confuses me even more... Hopefully I can reproduce this in my dev environment. I also see how the health is now showing until you go below and then heal back to it.

**Comment by TheUnderTaker11** [comment] 2017-01-17 23:00
Good news, reproducible in dev, problem is probably based on those ONLY working in the overworld. Expect a fix within 5-6 hours at the most. And about the "Losing all genes thing" no idea how to reproduce that, but from now on it won't stack on more hearts even if it does happen.
The problem came from me converting everything from just players to also working with mobs.

**Comment by Drase333** [comment] 2017-01-17 23:09
Just glad it led to fixing some issues, thanks for the quick response.

**Comment by TheUnderTaker11** [comment] 2017-01-17 23:12
I'll close this as soon as I put out an update with the fix, but if you find a re-producible way to lose all your genes I will get right on that also.

**Comment by TheUnderTaker11** [comment] 2017-01-18 02:16
The heart problem is harder to solve than expected. It's only a visual bug though so it's not a big deal if I put out an update before it is fixed. Updated version is up now, thank you for the bug report! I try and make it a point to respond and fix problems quickly because the way I see it, if you are willing to take the time to make a bug report instead of just removing the mod, then I'm more than willing to fix whatever the problem is so you can enjoy a bug free mod! (Or close to bug free)

**Closed as completed by TheUnderTaker11** 2017-01-18 02:16 UTC
Labels: bug

**Comment by TheUnderTaker11** [comment] 2017-01-18 02:36
Scratch that, shortly after closing this I found a fix, so I took down the old v0.17 and put up v0.18. Now your health will update visually!
