### ISSUE TITLE
still cant remove jump boost in 1.23 (havent tried others as yet)

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#154] opened 2020-03-16 00:15 UTC
i had a premade anti plasmid for jump boost waiting for this update. i know it was said to have been fixed in 1.22 but as it was stated  that mutation calculations were being fixed in 1.23 i skipped 1.22

anyway after applying the anti plasmid to my syringe, jump boost was moved to the last added gene in the list. so it didnt work. i then worked for a while and made a new anti plasmid for jump boost (in the hopes that the antiplasmid i made before the update was still operating under the old version's bug... still didnt work...

are there any tests you would like me to do?

**Comment by DartisXUI** [comment] 2020-03-16 00:18
could this be because i didnt start a new game? i know some mods have issues with configs not changing properly if youve already started the game

i will have to run a test world when i get time to isolate that chance

**Comment by clubpetey** [comment] 2020-03-16 23:36
AH HA! I think I found the cause...

Let's say that you have JUMP_BOOST and FLY genes.  After making the anti-plasmid for JUMP_BOOST you draw blood, purify it, add the anti-plasmid, and purify it again.

What you have now is a syringe with JUMP_BOOST, FLY and ANTI-JUMP_BOOST.  Adding the anti-plasmid doesn't remove JUMP_BOOST, it just adds the anti-gene.  During injection into your self, depending on the exact order in the tag structure, the anti-JUMP gene can be processed before or after the JUMP gene. Meaning it might work for some syringes and not others.

I can fix this for 1.24, in the mean time, or if you are playing with an older version, you can get around this if you have a clean blood sample (one with no genes) and use that one to add the anti-plasmid to.  As there is no JUMP gene and only an anti-JUMP gene, it will work correctly.

**Comment by clubpetey** [comment] 2020-03-17 09:01
Fixed in 1.24

**Closed as completed by clubpetey** 2020-03-17 09:01 UTC
Labels: bug
