### ISSUE TITLE
Client Side Crash - Incubator + Syringe with all Viral Agents (creating Black Death Potion)

### ISSUE THREAD

**Issue by boxers41** [TheUnderTaker11/GeneticsReborn#203] opened 2020-07-06 02:37 UTC
Hello, 

Upon attempting to create a Black Death Potion, a client side crash occurs. After extracting and purifying the blood with all viral agents placing the syringe in the incubator crashes the client. 

Crash Report Attached.

[message.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/4876498/message.txt)

Thanks,

-Boxers41

**Comment by clubpetey** [comment] 2020-08-13 06:06
Fixed in 1.29

**Comment by clubpetey** [comment] 2020-08-13 06:07
Also, dupe of #202

**Closed as completed** 2020-08-13 07:03 UTC
Labels: bug
