### ISSUE TITLE
Stepheight packet is used but not registered on Servers which leads to errors

### ISSUE THREAD

**Issue by ben-mkiv** [TheUnderTaker11/GeneticsReborn#96] opened 2019-10-15 17:42 UTC
https://github.com/TheUnderTaker11/GeneticsReborn/blob/7c420a8a7d5dfd59f29c5b27796275ded8f32bd4/src/main/java/com/theundertaker11/geneticsreborn/packets/GeneticsRebornPacketHandler.java#L19-L20

https://github.com/TheUnderTaker11/GeneticsReborn/blob/7c420a8a7d5dfd59f29c5b27796275ded8f32bd4/src/main/java/com/theundertaker11/geneticsreborn/event/PlayerTickEvent.java#L136-L139

also the step height might be affected by other mods and that could trigger an update packet!?

```
[17:25:42] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type com.theundertaker11.geneticsreborn.packets.StepHeightChange in channel GeneticsReborn
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
        at com.theundertaker11.geneticsreborn.event.PlayerTickEvent.checkStepAssist(PlayerTickEvent.java:138) [PlayerTickEvent.class:?]
        at com.theundertaker11.geneticsreborn.event.PlayerTickEvent.onPlayerTick(PlayerTickEvent.java:115) [PlayerTickEvent.class:?]
```

**Comment by clubpetey** [comment] 2019-10-15 20:22
I don't like the way I'm sending this message, I don't think I'm doing it exactly right.  So I'll re-approach this.

**Comment by TheUnderTaker11** [comment] 2019-10-15 20:28
https://github.com/TheUnderTaker11/Demonic-Intervention/tree/1.12.2/src/main/java/com/theundertaker11/demonicintervention/proxy/packets/servertoclient

https://github.com/TheUnderTaker11/Demonic-Intervention/blob/1.12.2/src/main/java/com/theundertaker11/demonicintervention/init/PacketRegistry.java

https://github.com/TheUnderTaker11/Demonic-Intervention/blob/b76f41abe9618628abcdd4a271ca89853173a934/src/main/java/com/theundertaker11/demonicintervention/capability/infusions/Infusions.java#L24

Not saying I do it the best way, but if I remember right I've tested these on a server myself, so you can use that for reference. @clubpetey

**Comment by clubpetey** [comment] 2019-10-16 07:57
Fixed in next release, I know how to do this now... Also @TheUnderTaker11  Your DI code I think has the same problem my code did.  The issue is this line of code, which exists in your IMessage handlers.

`EntityPlayerSP clientPlayer = Minecraft.getMinecraft().player;`

Both the EntityPlayerSP and Minecraft classes are client-side only.  so loading that class (in your packet handler's init() ) will attempt to load those classes which don't exist on a dedicated server and will crash the game....

`net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP`

There seems to be two ways to fix this, you can...
`if (ctx.side != Side.CLIENT) return;`
`EntityPlayer clientPlayer = Class.forName('net.minecraft.client.Minecraft').getMinecraft().player;`

This lazy-loading will work because the line of code that tries to load the Minecraft class is not run unless the side is CLIENT.  

The other option would be to create a function in your CommonProxy and ClientProxy called getClientPlayer().  With the common proxy returning null, and the client proxy returning Minecraft.getMinecraft.player.  This works because the client proxy class is never loaded unless on the client.  I used this route, it seemed cleaner. 

I wanted to explain this all out, as it took me almost 3 hours of digging through google/SO/Forge Forums to figure this out.  Hopefully those searching in the future will find this.

**Comment by ben-mkiv** [comment] 2019-10-16 11:46
i think you can just annotate the onMessage() method with
`@SideOnly(Side.CLIENT)`

that way a dedicated server will never see the method

**Comment by phil-flip** [comment] 2019-10-26 19:11
After we used the mod now for some time, the same error is now shown for us as well...
Kinda fills the logs really quickly. I know it sais its going to be fixed in the next release, but is there already a set date?

**Comment by clubpetey** [comment] 2019-10-26 19:39
The next release is in QA, it should be available by 11/2

**Comment by phil-flip** [comment] 2019-10-26 20:03
alright thanks

**Closed as completed** 2019-11-03 20:56 UTC
Labels: bug
