### ISSUE TITLE
Dragon's Breath...

### ISSUE THREAD

**Issue by Smrots** [TheUnderTaker11/GeneticsReborn#39] opened 2017-07-12 07:44 UTC
The dragon's breath ability doesn't work I tried changing the hotkey to several different ones(Ones that are not used.) and still nothing. This is for  v1.06

**Comment by TheUnderTaker11** [comment] 2017-07-13 20:26
Unable to reproduce, going to need more information.
If you gave yourself all genes with the debugging tool then that would be why though, in the current version it only adds more health and wither hit, I forgot to change it back after some testing.

**Comment by Pwnobbypure** [comment] 2017-07-24 16:46
I'm having the same problem, created the dragon's breath plasmid and injected it, but it doesn't work. I've made sure that nothing else it taking up the same keybind so it should work, although I am using v1.05. Was this fixed in v1.06?

**Comment by TheUnderTaker11** [comment] 2017-07-25 02:22
What MC version? And I'm going to need you to remove all other mods and try
it. Version 1.05 for 1.11.2 is unstable. I tested on 1.11 since he also
neglected to tell me the MC version.

**Comment by Smrots** [comment] 2017-07-25 02:25
It is for 1.11.2 and I can't remove all the mods. Either it plays nicely with what the pack what has it or it doesn't, for the most part, everything else works. It's just that one genetic modification.

**Comment by TheUnderTaker11** [comment] 2017-07-25 02:28
Well considering the blood purifier doesn't work in the version your using,
not sure how you got the gene. Im telling you to test it alone because I
wasn't able to reproduce it, i need to know if another core mod is messing
something up, and I won't be at a computer for awhile.

**Comment by Pwnobbypure** [comment] 2017-07-25 05:10
I'm using mc version 1.10.2. Is there no version that is fixed for this mc version?

**Comment by TheUnderTaker11** [comment] 2017-07-26 02:19
Sorry pwn, replying through mobile email so I thought you were the one who
replied saying you were using 1.11.2. I haven't tested the latest 1.10 but
will see if I can reproduce it when I get to a computer.

**Comment by TheUnderTaker11** [comment] 2017-07-27 00:06
Using 1.06 on both 1.10.2 and 1.11.2 I was unable to reproduce the problem. Is there a certain pack you guys are using this in or what? There has to be some common factor causing it to fail. Forge versions, mods that might change the ender dragon in some way (Not draconic evolution). I even went through all the trouble to start up a world with the downloaded version of the mod, went to the end, scraped the end dragon, made the ender dragon breath gene, and put it in myself just to make sure nothing in the processes was broken. I am completely unable to reproduce this.

**Comment by Smrots** [comment] 2017-07-27 02:17
The pack I am using is The Shivering Expanse on Curse/Twitch

**Comment by Pwnobbypure** [comment] 2017-07-27 18:03
Ok so after some testing I've realised that the Dragons Breath gene works in single player, but not multiplayer (even tho it's enabled in the config). We are using a modified version of FTB Infinity Lite 1.10 and Minecraft version 1.10.2. By modified I mean we've added some mods to the pack such as: Advanced solar panels, Modular Powersuits, Galacticraft (plus MorePlanets and ExtraPlanets addons), Ars Magica 2, Gravitation Suite, Ice and Fire, Security Craft, GravityGun, and MorePlayerModels, (I think those are all the extra mods). Hopefully this is enough information to give some lead.

**Comment by TheUnderTaker11** [comment] 2017-07-27 18:09
Just to confirm, does the teleport gene work on the server? If it does I
can look at the differences to see what I did wrong.

**Comment by Pwnobbypure** [comment] 2017-07-27 19:17
Yes the teleport gene works on the server

**Comment by TheUnderTaker11** [comment] 2017-07-31 22:43
Since it takes forever to test every little change I still haven't found the problem. Will get to it when I get to it I suppose.

**Comment by TheUnderTaker11** [comment] 2018-04-05 07:12
Fixed for both 1.10.2 and 1.11.2

**Closed as completed by TheUnderTaker11** 2018-04-05 07:12 UTC
Labels: bug
