### ISSUE TITLE
Basic Genes not able to be used to complete Genes in Plasmid Infuser

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#92] opened 2019-10-09 08:14 UTC
File:
*1.12-1.13

Issue:
*Only Trait specific genes (ie: Fly) can be used in Plasmid Infuser, "Basic" genes cannot be used.
(confirmed with Squid (Water Breathing); Blaze (Fly, Shoot Fireballs & Fire Proof) ).

*Pic 1:
Gene Not Set
https://www.dropbox.com/s/c3z9nad8hchti6k/2019-10-09_17.46.18.png?dl=0

Pic 2 & 3:
Adding first Blaze: Fire Proof Gene (0/24)
https://www.dropbox.com/s/wzztep3v5zy52kk/2019-10-09_17.46.30.png?dl=0
https://www.dropbox.com/s/xooyuvoccgn0nq1/2019-10-09_17.46.35.png?dl=0

Pic 4 & 5:
Proof that Trait Specific Genes work as intended (Blaze: Fire Proof) (4/24)
https://www.dropbox.com/s/7h6jvjy6rmufk1u/2019-10-09_17.47.05.png?dl=0
https://www.dropbox.com/s/tw2bnikhifs7hgx/2019-10-09_17.48.07.png?dl=0

Pic 6:
Trying to Shift+Click Blaze: Basic Gene - Failed
https://www.dropbox.com/s/r4fsibc64ghmg3a/2019-10-09_17.48.17.png?dl=0

Notes:
*Ordinary Click and Drop does not work either
*It does not seem to matter if the DNA Helix came from the Mob for the Trait or not.
(ie: Neither Basic Genes from Blazes or Squids work for Flight)

Pic 7 & 8:
It should be mentioned that I am using MultiMC, and while the downloaded File is 1.12-1.13, MultiMC has it as being Ver. 1.10. No way of knowing if this is important...
(I've had no isses with mods in MultiMC otherwise)
https://www.dropbox.com/s/0x3gt7vaub5sdpk/Genetics%20Reborn%201.12-1.13%20-%20MultiMC%201.10.png?dl=0
https://www.dropbox.com/s/lmw131sty4naf9l/Genetics%20Reborn%201.12-1.13.png?dl=0

**Comment by clubpetey** [comment] 2019-10-09 08:35
Basic Genes are not intended to be used in the Plasma Infuser.  The purpose of basic genes is to create the original "raw" plasmid.  Once you add the first trait-specific gene the plasmid is locked to that gene and from then on can only accept the correct gene type.

This is working as intended, however, I will look at why you are seeing an incorrect version number.

**Comment by DartisXUI** [comment] 2019-10-09 09:59
what was confusing about my initial comment on curseforge about basic genes not working in plasmid infuser?
why was i then asked to make a github issue report? ive never used github before, so theres yet another damn account to track.
it took about 2 hours to get everything set up, after being told this is *Not* intended... only to be told it was intended...
i dont appreciate being jerked around, not to mention needing 3 and a half stacks of blaze cells to get a single gene of flight that took about 3 hours to process - i get there needs to be grind, but thats rediculous - if you refuse to use basic genes, make the damn helxes stack or make an auto output/input upgrade to automate things *please!* (i could probably do it with ender io, but it would 2x or 3x the size of the setup)

**Comment by clubpetey** [comment] 2019-10-09 16:55
I looked at the comments on CurseForge, I'm not sure why @TheUnderTaker11 said it wasn't intended, as the code is pretty clear that basic genes are not usable for traits.  If they want to declare it firmly "a bug" I can change the code, but it's always been that way.

It could have been that they were saying that it should not take 3.5 stacks of cells to get a single gene... which is true, unless you are just SUPER unlucky.  Here's the math :

There is a 60 % chance to get a basic gene, since there is 3 genes a blaze can drop, there is a 13% chance you'll get a Fly gene.  Since flight is now ranked the second-most-powerful gene next to dragon breath it requires 25 fly-specific genes.  On average, it should take 3 stack of Blaze cells to get all the genes for flight.

In the last update I did increase the "difficulty" of earning flight by increasing the total number of genes to 25 from 12.  It's unlimited flight with no power cost, so some grind seemed appropriate, compared to other mods like Mekanism and Draconic Evolution that give you flight, but cost you power continuously.  I will let @TheUnderTaker11 comment if they feel 3 stacks on average is too much.  I will also run a test to make sure all the genes are being issued randomly.

If you want the machines to work faster, there are config setting to change the speed of the machines, or you can add overclockers, which greatly increase the power requirements.

Side note: The Wither and ghasts also grant the Fly gene at a higher rate... 26%.. so it only would take 1.5 stacks.

**Comment by clubpetey** [comment] 2019-10-09 21:12
I want to retract and correct part of my previous statement.  In reviewing the code, I did, in fact, block the basic gene from being processed in the Plasmid Infuser.  I apologize for thinking this was intended, in correcting other bugs about the wrong items being able to be inserted in the infuser, I took the basic Gene to be part of the bug.

I still want to make getting some traits more difficult, as some of them are pretty OP. So in the next release I'll add a "hardMode" config setting (default = false)  that will control this and a few other features in the future.

Next release will be out by 10/12

**Comment by DartisXUI** [comment] 2019-10-09 22:13
The only problem with going for ghast and withers for flight, is that it's best to have flight to get near them.
That's what made going for bats probably too op - I guess having blazes attack balances that out.
As for overclocking, it would not have helped. I was parallel processing as I always do. And I can only access all the machines in turn so quickly. But power was not an issue, my tree farm is very efficient.
As for the op nature of flight and other traits, my friends would not use advanced genetics at all, regardless of balancing. Same with enchantment plus for example. But I liked how these took some of the hardest things away, and have been a constant in my packs ever since ftb monster I think it was...
In this sense, a configurable Hard Mode seems like a great compromise. However people like my friends don't want to edit Configs, they consider it cheating; mind you, I do use them to up the standard 1:2 ore to ingot to 1:3 in tinkers construct smeltery (tested up to 1:27 to work)...
I would suggest make your hard mode default true, so those like me can opt out, rather than force people like my friends opt in, as I suspect there's more of them than there are those like me - I could be wrong though...

Man I'm going through some stuff, and that not your fault. Sorry for my saltiness. There was better ways to communicate things...

**Comment by clubpetey** [comment] 2019-10-09 22:31
With Hardmode 'off" it will do 3 things:
1. Allow the Basic Gene to give +1 to a Plasmid
2. set all Genes to require 24 "points"
3. Give the Bat the "Fly" gene back.

I'll set this up in the Wiki as well.  I hear you on the default being "true" but I'm going to configure the default to work as if no other Mods are installed, and more like the classic experience.  If you or your friends want the harder version, which i recommend for mod packs, then a one-line change in the config should be easy enough, there's lots of mods that are coming out with alternate recipes and "expert" modes that follow similar patterns.

Finally, regarding the stuff you are going through: no worries mate, keep up the positive thoughts, we appreciate you using our mods and the effort you spend reporting bugs to make them better. 

PLUR

**Comment by DartisXUI** [comment] 2019-10-09 23:04
+1 to this - sounds like the perfect balance between those that want a challenge and those that want a casual experience like myself

one more question: if youre allowing basic genes outside of hard mode, will any basic gene be accepted for any gene - or only basics from same mob?

**Comment by clubpetey** [comment] 2019-10-09 23:13
Any Basic gene from any mob will work.

**Comment by clubpetey** [comment] 2019-10-10 08:40
Released in 1.14

**Closed as completed by clubpetey** 2019-10-10 08:40 UTC
Labels: bug
